### ISSUE TITLE
Routing algorithm doesn't take access=no into account

### ISSUE THREAD

**Issue by matthewdarwin** [BikeOttawa/stressmodel#1]
I notice the BikeOttawa routing algorithm will use ways with access=no.  In particular, it will often suggest taking the (closed) Sentier des Voyageurs pathway in Hull.

(From Danny on OSM Canada slack channel)

**Comment by rcmc2020** [comment]
I have put in a fix for this specific case of access='no' but there are lots of other values for access.   I'm wondering specifically about access='private' but some of the other values might have to be considered (the numbers are recent counts):

`access=bicycle             : 1`
`access=customers           : 2`
`access=date_off=2010-10-31 : 2`
`access=delivery            : 1`
`access=designated          : 28`
`access=destination         : 360`
`access=no                  : 625`
`access=permissive          : 373`
`access=private             : 1041`
`access=seasonal            : 1`
`access=unknown             : 1`
`access=yes                 : 209`
`access=yes|yes|no          : 4`
`access=yes|yes|no|yes      : 1`
`access=yes|yes|yes|no      : 3`

**Comment by rcmc2020** [comment]
I haven't received any comments on the other access tags so I'm closing this issue.
